<h1>Administration</h1>

<a class="creer" href="newarticle.php">Créer un article</a>
    <table>
        <tr>
            <td><strong>Title</strong></td>
            <td><strong>Création date</strong></td>
            <td><strong>Auteur</strong></td>
            <td><strong>Categorie</strong></td>
        </tr>
        <?php foreach ($articles as $article): ?>
            <tr>
                <td><strong><?= $article['title'] ?></strong></td>
                <td><?= $article['creation_date'] ?></td>
                <td><?= $article['firstname'] ?>-<?= $article['lastname'] ?></td>
                <td><?= $article['name'] ?></td>
                <td>
                    <form action="admin.php" method="post">
                        <input type="hidden" name="sup" value="<?= $article['title'] ?>">
                        <input type="hidden" name="supC" value="<?= $article['POSTid'] ?>">
                        <button type="submit" value="Submit"><i class="fas fa-trash-alt"></i></button>
                    </form>
                </td>
                <td>
                  <button><a href="modif.php?thisID=<?= $article['POSTid'] ?>"><i class="fas fa-pencil-alt"></i></a></button>
                </td>
            </tr>
        <?php endforeach ?>
    </table>
