<h1>Inscription </h1>
<form method="post">
    <fieldset>
        <label for="firstName">Prenom</label><br>
        <input type="text" id="firstName" name="firstName"/><br>
        <label for="lastName">Nom</label><br>
        <input type="text" id="lastName" name="lastName"/><br>
        <label for="email">Email</label><br>
        <input type="email" id="email" name="email"/><br>
        <label for="password">Mot de passe</label><br>
        <input type="password" id="password" name="password"/><br><br>
        <button type="submit" value="Submit">Inscription</button>
    </fieldset>
    <a href="login.php">Deja Enregistré Connecter vous !</a>
</form>